CREATE TABLE user (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  street VARCHAR(150) NOT NULL,
  city VARCHAR(150) NOT NULL,
  zip_code VARCHAR(25) NOT NULL,
  country VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  phone VARCHAR(30) NOT NULL,
  hashed_password VARCHAR(255) NOT NULL,
  role ENUM('client', 'admin') NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE category (
 id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
 name VARCHAR(45) NOT NULL
);

CREATE TABLE product (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  category_id INT NOT NULL,
  trend_product VARCHAR(100) DEFAULT 'Aucun'
);

CREATE TABLE image (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  path VARCHAR(255) NOT NULL,
  product_id INT NOT NULL,
  FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE cart (
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  PRIMARY KEY (user_id, product_id),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE category_product (
  product_id INT NOT NULL,
  category_id INT NOT NULL,
  CONSTRAINT fk_category_product_product FOREIGN KEY (product_id) REFERENCES product (id),
  CONSTRAINT fk_category_product_category FOREIGN KEY (category_id) REFERENCES category (id)
);

CREATE TABLE favorite (
  user_id INT NOT NULL,
  product_id INT NOT  NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_favorite_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE orders (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status ENUM ('en attente de paiement','en préparation', 'expédiée', 'livrée', 'annulée') NOT NULL,
  user_id INT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  stripe_session_id VARCHAR(255) NULL,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES user (id),
  INDEX idx_stripe_session_id (stripe_session_id)
);

CREATE TABLE order_product (
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  quantity INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (order_id, product_id),
  CONSTRAINT fk_order_product_order FOREIGN KEY (order_id) REFERENCES orders (id),
  CONSTRAINT fk_order_product_product FOREIGN KEY (product_id) REFERENCES product (id)
);

CREATE TABLE review (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  rating INT NOT NULL,
  comment TEXT NULL DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES product (id)
);

INSERT INTO user (id, firstname, lastname, street, city, zip_code, country, email, phone, hashed_password, role)
VALUES 
(1, 'Jérôme', 'Melle', 'rue Lucien Faure', 'Bordeaux', '33300', 'France', 'innov.print.3d33@gmail.com', '0789989625', '$argon2i$v=19$m=16,t=2,p=1$UTUxeG1nUTdiUXVBRENUSg$zYYWOR7PYPIXG+DpCILT+A', 'admin'),
(2, 'Imane', 'Bichon', '10 rue Batailley', 'Bordeaux', '33300', 'France', 'imane.bichon@icloud.com', '+33 687654321', '$argon2i$v=19$m=16,t=2,p=1$eW92NlQ1UENPNVY5TVR2cg$bdvJULZC8d6MJqE2tNhYHA', 'client');

INSERT INTO category (id, name)
VALUES 
(1, "Figurines"),
(2, "Objets pratiques"),
(3, "Jeux"),
(4, "Divers");

INSERT INTO product (id, name, description, price, category_id, trend_product)
VALUES
(1, "Doigt de lecture", "Optimisez votre confort de lecture avec cette bague de lecture innovante imprimée en 3D en PLA. Discrète et légère, elle se porte facilement sur votre doigt pour vous permettre de garder la page sans effort, libérant vos mains pour un meilleur confort pendant vos moments de lecture. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, cette bague allie légèreté, robustesse et finition satinée, assurant un toucher agréable et une durabilité optimale. Son design ergonomique et compact s’adapte à toutes les tailles de doigts, offrant une prise en main stable et un maintien efficace des pages de livres, magazines ou journaux. Disponible en plusieurs coloris modernes, elle s’intègre parfaitement dans un univers minimaliste et élégant, combinant praticité et style. Cette bague de lecture est un accessoire astucieux et esthétique, idéal pour tous les passionnés de lecture souhaitant allier confort et design. Le livre sur la photo de présentation n'est pas inclus avec l'article. Dimensions en mm : L 80 l 50 h 10. Poids (en gr): 3", 2.00, 2, "Aucun"),
(2, "Pot de fleur rond", "Apportez une note végétale élégante et épurée à votre décoration grâce à ce pot de fleur rond imprimé en 3D en PLA. Son design simple et harmonieux met en valeur la forme naturelle des plantes tout en s’intégrant facilement dans tout type d’intérieur. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce pot léger renvoit un rendu soigné. Parfait pour accueillir des plantes grasses, des cactus ou des petites boutures, il trouve facilement sa place sur une table, une étagère, un rebord de fenêtre ou un bureau. Disponible en plusieurs couleurs modernes et sobres, ce pot rond s’accorde aussi bien avec une décoration contemporaine que scandinave ou bohème. À la fois pratique et décoratif, il constitue une belle idée de cadeau ou un élément idéal pour créer une série de compositions végétales personnalisées. Dimensions (en mm): diam 120 h 145. Poids (en gr): 150.", 7.00, 2, "Produit du moment"),
(3, "Chat allongé", "Apportez une touche de douceur et de sérénité à votre intérieur avec cette figurine de chat allongé imprimée en 3D en PLA. Finement conçue, cette pièce décorative capture l’élégance naturelle du félin dans une posture paisible, idéale pour créer une ambiance apaisante et chaleureuse. Réalisé en PLA, un matériau biosourcé et respectueux de l’environnement, ce chat décoratif est à la fois résistant et doté d’une finition satinée qui met en valeur chaque courbe du modèle. Son format compact lui permet de trouver facilement sa place sur une étagère, un bureau, une table de chevet ou au sein d’une composition décorative plus large. Disponible en plusieurs coloris, il s’harmonise parfaitement avec des univers déco variés : minimalistes, contemporains ou naturels. Ce petit compagnon silencieux séduira autant les amateurs de chats que les passionnés d’objets imprimés en 3D, et constitue une idée cadeau originale et pleine de tendresse.", 3.00, 1, "Produit du moment"),
(4, "Chiot", "Ajoutez une note tendre et attachante à votre décoration avec ce chiot assis imprimé en 3D en PLA. Représenté dans une posture calme et attentive, ce petit compagnon dégage une douceur qui ravira les amoureux des animaux comme les amateurs de belles pièces décoratives. Conçu en PLA, un matériau biosourcé, léger et respectueux de l’environnement, ce chiot bénéficie d’une finition satinée qui met en valeur les détails de sa silhouette tout en assurant une bonne résistance dans le temps. Son format compact lui permet de s’installer facilement sur une étagère, un bureau, une commode ou une table d’appoint. Disponible en plusieurs coloris, il s’accorde aussi bien à une chambre d’enfant qu’à un intérieur moderne, naturel ou cocooning. À la fois mignon et élégant, ce chiot assis constitue une belle idée de cadeau, ou un élément décoratif discret pour apporter une touche d’affection à votre quotidien.", 3.00, 1, "Produit du moment"),
(5, "Écureuil", "Apportez une touche de nature et de malice à votre intérieur avec ce charmant écureuil imprimé en 3D en PLA. Figé dans une posture assise, il évoque la curiosité et l’agilité de ce petit animal des forêts, tout en ajoutant une note moderne à votre décoration. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, cet écureuil associe légèreté, robustesse et une belle finition satinée qui souligne les détails de sa silhouette. Compact et décoratif, il trouve facilement sa place sur une étagère, un rebord de fenêtre, une table ou au sein d’une composition automnale. Disponible en plusieurs coloris, il s’intègre harmonieusement dans des décors d’inspiration naturelle, rustique ou scandinave. Parfait pour les amoureux de la faune ou les passionnés d’objets originaux imprimés en 3D, cet écureuil constitue un cadeau à la fois ludique et élégant.", 3.00, 1, "Produit du moment"),
(6, "Lapin", "Apportez une note de douceur et de délicatesse à votre intérieur avec ce lapin imprimé en 3D en PLA. Avec son expression paisible, ce petit compagnon évoque la tranquillité et la tendresse, tout en s’intégrant harmonieusement à tout type de décoration. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce lapin allie légèreté, solidité et finition satinée, mettant en valeur les détails soignés du modèle. Son format compact en fait un objet déco idéal à poser sur une étagère, un bureau, un buffet ou au cœur d’une composition saisonnière. Disponible en plusieurs coloris, il se marie facilement avec des ambiances naturelles, scandinaves ou enfantines. Ce lapin décoratif séduira petits et grands, et constitue une idée cadeau pleine de charme pour les amoureux des animaux et des objets imprimés en 3D.", 4.00, 1, "Aucun"),
(7, "Lion", "Ajoutez une touche de majesté et de caractère à votre décoration avec ce lion imprimé en 3D en PLA. Représenté dans une posture noble et sereine, ce roi de la savane incarne la force tranquille et l’élégance naturelle, tout en apportant une note moderne et raffinée à votre intérieur. Conçu en PLA, un matériau biosourcé et respectueux de l’environnement, ce lion combine robustesse, légèreté et une finition satinée qui met en valeur les détails de sa crinière et de sa silhouette. Sa taille compacte permet de l’installer facilement sur une étagère, un bureau ou une console, où il devient un véritable objet de caractère. Disponible en plusieurs coloris, il s’intègre aussi bien dans des univers modernes que dans des ambiances plus naturelles. Idéal pour les amateurs d’animaux majestueux ou les passionnés de déco originale, ce lion en 3D constitue un cadeau audacieux et inspirant.", 3.00, 1, "Produit du moment"),
(8, "Panda", "Apportez une touche de douceur et de nature à votre décoration avec cette figurine de panda, imprimée en 3D en PLA de qualité. Conçue avec précision, cette pièce met en valeur les traits caractéristiques de l’animal emblématique, avec des finitions nettes et un rendu satiné qui valorisent chaque détail. Fabriquée à partir de PLA biosourcé, cette figurine allie légèreté, solidité et respect de l’environnement. Sa forme équilibrée et ses volumes bien définis en font un objet décoratif discret et élégant, idéal pour personnaliser un bureau, une étagère ou une vitrine. Cette pièce s’adresse autant aux amateurs de décoration contemporaine qu’aux passionnés d’animaux et de créations imprimées en 3D. Elle constitue également un cadeau original et responsable, à offrir en toute occasion. Dimensions en mm : L 110 l 90 h 80. Poids (en gr): 110", 8.00, 1, "Aucun"),
(9, "Pokeball Arcanin", "Découvrez cette superbe Pokéball Arcanin, imprimée en 3D avec précision à partir de PLA de haute qualité. Inspirée de l’univers Pokémon, cette pièce décorative met à l’honneur Arcanin, le Pokémon légendaire réputé pour sa prestance et sa puissance. Le design soigné de cette Pokéball associe des lignes nettes et des finitions impeccables, offrant un rendu fidèle et esthétique. Sa conception en PLA biosourcé garantit légèreté, solidité et respect de l’environnement, tout en apportant une finition satinée agréable au toucher et visuellement valorisante. Idéale pour les collectionneurs et les passionnés de la licence Pokémon, cette Pokéball peut être exposée sur une étagère, un bureau ou dans une vitrine dédiée. Elle constitue également une excellente idée cadeau pour les amateurs de culture geek et d’objets imprimés en 3D. Poids (en gr): 100.", 11.00, 1, "Aucun"),
(10, "Pokeball Ronflex", "Apportez une touche de nostalgie et de collection à votre intérieur avec cette Pokéball Ronflex imprimée en 3D en PLA de qualité. Fidèle à l’univers des célèbres jeux vidéo et séries animées, cette pièce décorative met à l’honneur Ronflex, le Pokémon emblématique reconnu pour sa force et son caractère paisible. Conçue avec soin, cette Pokéball présente des finitions nettes et des détails précis, faisant d’elle un objet à la fois décoratif et collector. Sa fabrication en PLA assure une impression légère, durable et respectueuse de l’environnement. La combinaison des couleurs caractéristiques et l’aspect satiné du matériau renforcent le réalisme et l’esthétique de cette pièce. Parfaite pour les amateurs de l’univers Pokémon, cette Pokéball trouvera naturellement sa place sur une étagère, un bureau ou dans une vitrine de collection. Elle peut également constituer une idée cadeau originale et personnalisée pour les passionnés de culture pop et d’impression 3D. Poids (en gr): 100.", 11.00, 1, "Aucun"),
(11, "Pot de fleur chien", "Apportez une touche ludique et attachante à votre intérieur avec ce pot de fleur en forme de chien, imprimé en 3D en PLA. Alliant fonction décorative et clin d’œil animalier, ce modèle original est parfait pour accueillir de petites plantes, succulentes ou boutures tout en égayant votre espace. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce pot allie légèreté, robustesse et une finition satinée soignée. Son design en forme de chien, à la fois mignon et moderne, en fait un objet déco unique qui trouve facilement sa place sur un rebord de fenêtre, un bureau, une étagère ou même dans une chambre d’enfant. Disponible en plusieurs coloris, il s’harmonise avec différents styles de décoration, du plus contemporain au plus fantaisiste. Ce pot de fleur chien ravira les amoureux des animaux et des plantes, et constitue une idée cadeau aussi pratique qu’originale. Dimensions (en mm): L 180 l 150 h 130. Poids (en gr): 170.", 7.00, 2, "Aucun"),
(12, "Sifflet anti-agression", "Ce sifflet anti-agression imprimé en 3D en PLA bleu est un accessoire de sécurité pratique et indispensable à avoir à portée de main. Conçu pour être léger, compact et facile à transporter, il se glisse aisément dans une poche, un sac ou se fixe à un trousseau de clés grâce à son anneau porte-clés inclus. Sa fabrication en PLA, un matériau léger, résistant et respectueux de l’environnement, garantit à la fois robustesse et durabilité. Sa teinte bleu vif le rend facilement repérable en cas de besoin rapide. Ce sifflet a été pensé pour produire un son puissant et strident, capable d’attirer l’attention immédiate des personnes à proximité et de dissuader un agresseur potentiel. Idéal pour les joggeurs, les randonneurs, les étudiants ou toute personne souhaitant se sentir plus en sécurité au quotidien, ce sifflet peut également être utilisé dans le cadre d’activités sportives ou d’événements pour signaler une situation ou donner un signal sonore clair. Discret et esthétique, son design imprimé en 3D présente des finitions soignées et une ergonomie agréable, assurant une bonne prise en main. Un petit accessoire utile qui allie efficacité, simplicité et engagement pour des matériaux plus responsables.", 3.00, 2, "Aucun"),
(13, "Étui brosse à dents", "Alliez praticité et design avec cet étui de brosse à dents imprimé en 3D en PLA, idéal pour protéger votre brosse à dents à la maison comme en déplacement. Conçu avec soin, il assure une protection hygiénique tout en apportant une touche moderne et personnalisée à votre trousse de toilette. Fabriqué en PLA, un matériau biosourcé, léger et respectueux de l’environnement, cet étui est à la fois robuste, facile à nettoyer et doté d’une finition satinée agréable au toucher. Sa forme compacte et ergonomique convient à la plupart des brosses à dents standards. Disponible en plusieurs coloris, il est parfait pour les voyages, le sport ou tout simplement pour garder votre brosse à dents à l’abri de la poussière. Pratique, esthétique et écologique, cet étui est une excellente alternative aux produits plastiques classiques et constitue une idée cadeau utile pour petits et grands. La brosse à dent sur la photo de présentation n'est pas incluse avec l'étui. Dimensions (en mm): L 220 l 33  h 20. Poids (en gr): 78.", 5.50, 2, "Aucun"),
(14, "Chat", "Apportez une note de douceur et de charme à votre intérieur avec cette figurine de chat imprimée en 3D en PLA. Avec ses lignes délicates et son expression calme, ce petit compagnon incarne la sérénité et la complicité, tout en s’intégrant harmonieusement à tout type de décoration. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce chat allie légèreté, solidité et finition satinée, mettant en valeur les courbes élégantes et les détails raffinés du modèle. Son format compact en fait un objet déco parfait à poser sur une étagère, un bureau, une table de chevet ou au cœur d’une composition végétale. Disponible en plusieurs coloris, il s’adapte aisément à des ambiances naturelles, modernes ou cosy. Cette figurine de chat séduira petits et grands, et constitue une idée cadeau pleine de tendresse pour les amoureux des félins et des objets imprimés en 3D.", 3.00, 1, "Aucun"),
(15, "Chien", "Apportez une note chaleureuse et pleine de douceur à votre intérieur avec cette figurine de chien imprimée en 3D en PLA. Ce compagnon évoque la fidélité et la tendresse, tout en s’intégrant harmonieusement à tout type de décoration. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce chien allie légèreté, solidité et finition satinée, mettant en valeur les détails soignés et la silhouette équilibrée du modèle. Son format compact en fait un objet déco idéal à poser sur une étagère, un bureau, une table basse ou au cœur d’une composition végétale. Disponible en plusieurs coloris, il se marie facilement avec des ambiances naturelles, modernes ou cosy. Cette figurine de chien séduira petits et grands, et constitue une idée cadeau pleine de tendresse pour les amoureux des chiens et des objets imprimés en 3D.", 4.00, 1, "Aucun"),
(16, "Support éponge maquillage", "Apportez une touche d’élégance et de praticité à votre routine beauté avec ce support d’éponge de maquillage imprimé en 3D en PLA. Conçu pour maintenir votre éponge propre et aérée, il allie design soigné et fonctionnalité pour un rangement optimal et hygiénique. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce support allie légèreté, robustesse et finition satinée, mettant en valeur ses formes épurées et sa stabilité. Compact et discret, il trouve facilement sa place sur une coiffeuse, un plan de salle de bain ou une étagère. Disponible en plusieurs coloris, il s’adapte harmonieusement à des univers modernes, minimalistes ou naturels. Ce support d’éponge de maquillage est un accessoire pratique et esthétique, parfait pour organiser votre espace beauté avec style. L'éponge de présentation sur l'image n'est pas incluse avec le support.", 2.00, 2, "Aucun"),
(17, "Cube infini", "Apportez une touche de sérénité et de concentration à votre quotidien avec ce cube infini anti-stress imprimé en 3D en PLA. Conçu pour offrir un mouvement fluide et continu, ce petit objet relaxant aide à réduire le stress tout en stimulant la créativité et la détente. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce cube allie légèreté, robustesse et finition satinée, mettant en valeur son design ingénieux et ses formes épurées. Compact et facile à manipuler, il s’emporte partout — au bureau, à la maison ou en déplacement — pour vous accompagner dans vos moments de pause. Disponible en plusieurs coloris, il s’intègre aisément dans des univers modernes, minimalistes ou professionnels. Ce cube infini anti-stress est un accessoire à la fois fonctionnel et esthétique, idéal pour offrir ou s’offrir un moment de calme et de bien-être.", 4.00, 3, "Aucun"),
(18, "Dinosaure", "Apportez une touche ludique et originale à votre intérieur avec cette figurine de dinosaure imprimée en 3D en PLA. Avec ses formes stylisées et son allure dynamique, ce petit compagnon évoque l’aventure et la curiosité, tout en s’intégrant facilement à des décors modernes ou enfantins. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce dinosaure allie légèreté, robustesse et finition satinée, mettant en valeur les détails soignés de sa silhouette unique. Son format compact en fait un objet déco idéal à poser sur une étagère, un bureau, une table de chevet ou au cœur d’une composition originale. Disponible en plusieurs coloris, il se marie parfaitement avec des ambiances ludiques, contemporaines ou naturelles. Cette figurine de dinosaure séduira petits et grands, et constitue une idée cadeau pleine de fantaisie pour les passionnés de préhistoire et de design imprimé en 3D.", 4.00, 1, "Aucun"),
(19, "Lapin qui dort", "Apportez une touche de sérénité et de douceur à votre intérieur avec cette figurine de lapin aux yeux fermés, imprimée en 3D en PLA. Avec ses formes arrondies et son expression paisible, ce petit compagnon évoque la tranquillité et le calme, tout en s’intégrant harmonieusement à tout type de décoration. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce lapin aux yeux fermés allie légèreté, robustesse et finition satinée, mettant en valeur ses courbes délicates et les détails soignés de son visage serein. Son format compact en fait un objet déco parfait à poser sur une étagère, un bureau, une table de chevet ou au cœur d’une ambiance apaisante. Disponible en plusieurs coloris, il s’adapte aisément à des ambiances naturelles, minimalistes ou cosy. Cette figurine de lapin aux yeux fermés séduira petits et grands, et constitue une idée cadeau pleine de charme pour les amateurs de calme et de douceur.", 4.00, 1, "Aucun"),
(20, "Lapin mignon", "Apportez une touche de douceur et de tendresse à votre intérieur avec cette figurine de lapin mignon imprimée en 3D en PLA. Avec ses formes rondes et son expression adorable, ce petit compagnon évoque la gentillesse et la sérénité, tout en s’intégrant parfaitement à tout type de décoration. Imprimé en PLA, un matériau biosourcé et respectueux de l’environnement, ce lapin mignon allie légèreté, robustesse et finition satinée, mettant en valeur ses courbes délicates et ses détails charmants. Son format compact en fait un objet déco idéal à poser sur une étagère, un bureau, une table de chevet ou au cœur d’une composition décorative. Disponible en plusieurs coloris, il s’harmonise facilement avec des ambiances douces, naturelles ou enfantines. Cette figurine de lapin mignon séduira petits et grands, et constitue une idée cadeau pleine de charme pour tous les amoureux des animaux et des objets imprimés en 3D.", 4.00, 1, "Aucun"),
(21, "Licorne", "Apportez une touche magique et féerique à votre intérieur avec cette figurine de licorne imprimée en 3D en PLA. Avec ses formes élégantes et sa posture gracieuse, cette créature mythique évoque la douceur, la pureté et l’imaginaire, tout en s’intégrant harmonieusement à tout type de décoration. Imprimée en PLA, un matériau biosourcé et respectueux de l’environnement, cette licorne allie légèreté, robustesse et finition satinée, mettant en valeur les détails raffinés de sa crinière et de sa silhouette délicate. Son format compact en fait un objet déco idéal à poser sur une étagère, un bureau, une table de chevet ou au cœur d’une ambiance enchantée. Disponible en plusieurs coloris, elle s’adapte parfaitement à des univers doux, enfantins ou romantiques. Cette figurine de licorne séduira petits et grands, et constitue une idée cadeau pleine de charme pour tous les passionnés de magie et d’objets imprimés en 3D.edécouvrez le plaisir des jeux classiques avec ce jeu de morpion imprimé en 3D en PLA de qualité. Composé d’un plateau et de ses pions, cet ensemble offre une finition soignée et des lignes nettes pour un rendu esthétique et durable. Le plateau, structuré en cases parfaitement délimitées, permet de jouer facilement à deux, en intérieur comme en extérieur. Les pions, conçus en PLA biosourcé, assurent une bonne prise en main et une résistance à l’usage répété. Disponibles en deux coloris distincts pour chaque joueur, ils garantissent une lisibilité optimale pendant la partie. Léger et facile à transporter, ce jeu de morpion est idéal pour animer vos pauses, vos déplacements ou vos moments en famille. Sa conception en impression 3D lui confère un aspect moderne et personnalisable, s’intégrant aussi bien dans une salle de jeux que comme élément décoratif sur un bureau ou une table basse Parfait pour les amateurs de jeux traditionnels et d’objets imprimés en 3D, il constitue également une idée cadeau originale et conviviale.", 5.00, 1, "Aucun"),
(22, "Jeu de morpion", "Redécouvrez le plaisir du jeu avec ce morpion revisité, imprimé en 3D en PLA, un matériau écologique, biosourcé et respectueux de l’environnement. Conçu pour allier simplicité et élégance, ce jeu emblématique se présente dans une version moderne aux lignes épurées et aux finitions soignées. Léger, compact et résistant, il se glisse facilement dans un sac ou un tiroir pour être toujours à portée de main, que ce soit pour une pause au bureau, un moment ludique à la maison ou une activité nomade en voyage. Chaque pièce du jeu a été pensée pour offrir une prise en main agréable et un rendu visuel harmonieux. Disponible en plusieurs combinaisons de couleurs, il s’adapte à tous les styles, qu’ils soient ludiques, minimalistes ou contemporains. Ce jeu de morpion 3D est à la fois un bel objet décoratif et un compagnon de détente convivial, parfait pour partager un moment de stratégie et de complicité. Un cadeau original et durable à offrir ou à s’offrir, pour petits et grands.", 6.00, 3, "Aucun"),
(23, "Oeuf décoration", "Apportez une touche délicate et poétique à votre décoration avec cet œuf décoratif imprimé en 3D en PLA, renfermant un petit lapin adorable à l’intérieur. Ce duo charmant évoque douceur et renouveau, parfait pour sublimer vos espaces de vie avec une note printanière et raffinée. Confectionné en PLA, un matériau biosourcé et respectueux de l’environnement, cet objet allie légèreté, robustesse et finition satinée, mettant en valeur les détails finement travaillés de l’œuf ajouré et du lapin miniature niché à l’intérieur. Son format compact permet de l’exposer sur une étagère, une table ou une console, apportant une touche d’élégance et de tendresse à votre intérieur. Disponible en plusieurs coloris, il s’intègre aisément à des ambiances naturelles, romantiques ou saisonnières. Cet œuf décoratif avec petit lapin est une idée cadeau pleine de charme, idéale pour célébrer les moments doux et poétiques de la vie.", 5.00, 4, "Aucun"),
(24, "Ouvre bouteille", "Emportez toujours avec vous un accessoire pratique et stylé grâce à cet ouvre-bouteille porte-clé imprimé en 3D en PLA. Compact et léger, il combine fonctionnalité et design soigné pour vous accompagner partout, que ce soit lors de vos sorties entre amis ou de vos moments détente. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, cet ouvre-bouteille allie robustesse et finition satinée, mettant en valeur ses formes épurées et son aspect moderne. Facile à accrocher à vos clés, il assure une prise en main confortable et une ouverture efficace de vos bouteilles. Disponible en plusieurs coloris, il s’adapte à tous les styles et constitue un cadeau pratique et original, parfait pour les amateurs d’objets astucieux et durables.", 2.00, 2, "Aucun"),
(25, "Pancarte jardin", "Organisez facilement votre potager, vos jardinières ou votre balcon avec cet ensemble de pancartes de semis imprimées en 3D. Conçues en PLA de qualité et disponibles en plusieurs coloris, ces étiquettes décoratives et pratiques permettent d’identifier clairement vos plantations tout en apportant une touche colorée à vos espaces verts. Chaque pancarte est soigneusement réalisée avec une finition lisse et résistante, assurant une bonne tenue en extérieur comme en intérieur. Elles sont marquées du nom des différentes cultures — telles que Menthe, Carottes, Courgettes, Basilic, Persil ou encore Tomates — facilitant ainsi le repérage de vos semis et plantations au quotidien. Fabriquées en PLA biosourcé et respectueux de l’environnement, ces étiquettes jardin allient durabilité et esthétique. Leur format pratique permet de les planter directement dans la terre ou dans des pots, pour une organisation simple et élégante de vos cultures aromatiques, potagères ou florales. Parfaites pour les jardiniers amateurs ou confirmés, elles constituent également une idée cadeau originale et utile pour les passionnés de jardinage et de décoration naturelle. Dimensions (en mm): L 70 l 10 h 150. Poids (en gr): 50.", 1.50, 2, "Aucun"),
(26, "Pièces d'échecs", "Redécouvrez le jeu d’échecs avec ces pions imprimés en 3D en PLA de qualité. Chaque pièce est conçue avec précision pour respecter les formes traditionnelles du jeu, tout en bénéficiant d’une finition moderne et soignée. Fabriqués en PLA biosourcé et respectueux de l’environnement, ces pions allient légèreté et robustesse. Leur texture satinée et leur découpe nette assurent une excellente prise en main et un rendu esthétique valorisant sur tout type de plateau. Disponibles en plusieurs coloris sur demande, ces pions peuvent être utilisés pour compléter un jeu existant, personnaliser un échiquier ou constituer un élément décoratif original. Ils conviennent aussi bien à un usage de loisir qu’à des présentations ou animations autour du jeu d’échecs. Grâce à la qualité de leur impression et à la précision des détails, ces pions sont idéals pour les passionnés de jeux de stratégie et les amateurs d’objets imprimés en 3D. Le plateau de jeu sur l'image de présentation n'est pas inclus avec lespions.", 15.00, 3, "Aucun"),
(27, "Porte cartes à jouer", "Apportez une touche pratique et élégante à vos parties de jeux de société avec ce support de cartes à jouer imprimé en 3D en PLA. Conçu pour maintenir vos cartes bien en place, il facilite la manipulation et améliore votre confort de jeu tout en ajoutant une note design à votre table. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce support allie légèreté, solidité et finition satinée, mettant en valeur ses lignes soignées et sa forme ergonomique. Compact et stable, il s’adapte facilement à toutes les tailles de cartes standard, que ce soit pour les jeux de cartes traditionnels ou modernes. Disponible en plusieurs coloris, il s’intègre aisément dans des ambiances ludiques, contemporaines ou conviviales. Ce support de cartes à jouer est un accessoire à la fois fonctionnel et esthétique, idéal pour les amateurs de jeux souhaitant allier praticité et style. Les cartes à jouer sur l'image de présentation ne sont pas incluses avec le support. Dimensions (en mm): L 160 l 23 h 30. Poids (en gr): 20.", 5.00, 3, "Aucun"),
(28, "Porte cartes de visite", "Apportez une touche d’élégance et de professionnalisme à votre bureau avec ce porte-cartes de visite imprimé en 3D en PLA. Son design épuré et fonctionnel vous permet de présenter vos cartes avec style tout en gardant votre espace de travail organisé et soigné. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce porte-cartes allie légèreté, robustesse et finition satinée, mettant en valeur ses lignes nettes et sa structure stable. Compact et pratique, il s’adapte parfaitement à un bureau, une réception ou un espace de travail, facilitant l’accès à vos cartes lors de vos échanges professionnels. Disponible en plusieurs coloris, il s’intègre harmonieusement à des univers modernes, minimalistes ou classiques. Ce porte-cartes de visite est un accessoire fonctionnel et élégant, idéal pour valoriser votre image professionnelle ou offrir un cadeau utile et raffiné. Les cartes de visite sur l'image de présentation ne sont pas incluses avec le support. Dimensions (en mm): L 100 l 65 h 88. Poids (en gr): 45.", 6.00, 2, "Aucun"),
(29, "Porte crayons rond", "Apportez une touche d’élégance et de simplicité à votre espace de travail avec ce pot à crayons rond imprimé en 3D en PLA. Sa forme arrondie et épurée offre un design harmonieux qui s’intègre facilement à tous les styles de bureau, tout en apportant une organisation pratique à vos outils d’écriture. Conçu en PLA, un matériau biosourcé et respectueux de l’environnement, ce pot à crayons allie légèreté, robustesse et finition satinée, mettant en valeur ses courbes douces et son aspect soigné. Son format compact permet de ranger stylos, crayons, pinceaux et autres accessoires sur un bureau, une table ou une étagère, tout en optimisant l’espace. Disponible en plusieurs coloris, il se marie aisément avec des univers modernes, minimalistes ou naturels. Ce pot à crayons rond est un accessoire aussi fonctionnel qu’esthétique, idéal pour organiser votre espace de travail ou offrir un cadeau pratique et élégant.Dimensions (en mm): diam 80 h 97. Poids (en gr): 65.", 6.00, 2, "Aucun"),
(30, "Pot de fleur", "Apportez une touche moderne et graphique à votre intérieur avec ce pot de fleur pentagonal imprimé en 3D en PLA. Sa forme géométrique unique et ses lignes épurées offrent un design original qui valorise élégamment vos plantes tout en s’intégrant parfaitement à tout type de décoration. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce pot allie légèreté, solidité et finition satinée, mettant en valeur ses angles précis et son esthétique soignée. Compact et polyvalent, il est idéal pour accueillir succulentes, petites plantes ou boutures, et trouve facilement sa place sur une étagère, un bureau, un rebord de fenêtre ou une table. Disponible en plusieurs coloris modernes, il s’adapte harmonieusement aux ambiances contemporaines, minimalistes ou naturelles. Ce pot de fleur pentagonal constitue un choix pratique et décoratif, parfait pour créer des compositions végétales originales ou pour offrir un cadeau design et écoresponsable.", 6.00, 2, "Aucun"),
(31, "Petit pot de fleur", "Ajoutez une touche décorative discrète et soignée à votre intérieur avec ce petit pot de fleur imprimé en 3D en PLA. Conçu avec précision, ce modèle compact est idéal pour accueillir de petites plantes, des succulentes ou des boutures. Sa fabrication en PLA, un matériau biosourcé et respectueux de l’environnement, garantit un rendu à la fois léger et résistant, avec une finition satinée de qualité. Sa taille réduite en fait un accessoire parfait pour sublimer un coin de bureau, une étagère, un rebord de fenêtre ou même une table de chevet. Disponible en plusieurs coloris, ce petit pot de fleur se marie aisément avec des styles de décoration modernes, minimalistes ou naturels. Il constitue également un choix pratique et esthétique pour réaliser des compositions végétales en série ou pour offrir en cadeau. Dimensions (en mm): L 75 l 75 h 63. Poids (en gr): 65.", 5.00, 2, "Aucun"),
(32, "Poule", "Adoptez cette charmante poule, une pièce décorative originale imprimée en 3D avec précision à partir de PLA vert. Son design soigné et ses courbes douces en font un objet à la fois ludique et élégant, idéal pour personnaliser votre intérieur, une cuisine ou un bureau avec une touche de fantaisie. Grâce à l’impression 3D, chaque détail est minutieusement travaillé pour offrir un rendu homogène et de qualité. Fabriquée en PLA, un matériau biodégradable et respectueux de l’environnement, cette poule décorative associe esthétique et engagement écologique. Elle s’intégrera parfaitement dans une décoration moderne, rustique ou décalée et peut aussi constituer une idée de cadeau originale pour les amateurs de créations artisanales ou d’objets imprimés en 3D.", 3.00, 1, "Aucun"),
(33, "Sapin décoratif", "Ajoutez une touche de modernité et d’élégance à votre intérieur avec cette pyramide décorative imprimée en 3D en PLA orangé. Sa silhouette géométrique aux lignes épurées et ses multiples facettes lui confèrent un aspect contemporain qui saura s’intégrer facilement dans différents styles de décoration, qu’ils soient modernes, minimalistes ou plus chaleureux. Imprimée en 3D avec précision, cette pièce offre des finitions soignées et une qualité de fabrication qui met en valeur le rendu du PLA, un matériau à la fois léger et résistant, connu pour son aspect lisse et satiné. Sa teinte orangée apporte une touche lumineuse et chaleureuse à vos espaces, qu’elle soit posée sur une étagère, une table basse ou un bureau.Polyvalente, cette pyramide peut être utilisée comme simple objet décoratif, comme presse-papiers ou comme élément de mise en scène pour vos photos et créations artistiques. Fabriquée à partir de PLA, un plastique biodégradable issu de ressources renouvelables, elle allie esthétique et démarche écoresponsable. Une idée de cadeau originale et design pour les amateurs de décoration contemporaine et d’objets imprimés en 3D.", 4.00, 4, "Aucun"),
(34, "Support brosse à dents", "Apportez une touche pratique et élégante à votre salle de bain avec ce support de brosse à dents imprimé en 3D en PLA. Conçu pour accueillir et organiser vos brosses à dents, il allie fonctionnalité et design soigné, offrant une solution hygiénique et esthétique au quotidien. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce support allie légèreté, robustesse et finition satinée, mettant en valeur ses formes épurées et sa stabilité. Compact et polyvalent, il s’adapte facilement à différents modèles de brosses à dents et se place aisément sur un lavabo ou une étagère. Disponible en plusieurs coloris, il s’intègre harmonieusement dans des salles de bain modernes, minimalistes ou naturelles. Ce support de brosse à dents est un accessoire pratique et décoratif, parfait pour organiser votre espace tout en apportant une touche design. La brosse à dents sur l'image de présentation n'est pas incluse avec le support. Dimensions (en mm): L 80 l 44 h 103. Poids (en gr): 35.", 6.50, 2, "Aucun"),
(35, "Boîte rangement jeux Switch", "Organisez vos jeux Nintendo Switch avec style grâce à cette boîte de rangement imprimée en 3D en PLA. Conçue pour accueillir et protéger vos cartouches de jeux, elle offre une solution pratique et élégante pour garder votre collection bien rangée et à portée de main. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, cette boîte allie légèreté, robustesse et finition satinée, mettant en valeur un design fonctionnel et compact. Son format optimisé permet de stocker plusieurs cartouches en toute sécurité, tout en facilitant leur accès rapide lors de vos sessions de jeu. Disponible en plusieurs coloris, elle s’intègre parfaitement à des espaces modernes et geek, apportant une touche de personnalisation à votre setup gaming. Cette boîte de rangement pour jeux Switch est un accessoire aussi pratique qu’esthétique, idéal pour les passionnés souhaitant allier organisation et design.", 5.00, 3, "Aucun"),
(36, "Support écran", "Offrez à votre téléphone un support pratique et esthétique avec ce support de téléphone imprimé en 3D en PLA orange. Conçu pour allier simplicité, robustesse et design moderne, cet accessoire indispensable trouve facilement sa place sur un bureau, une table de chevet ou un plan de travail. Grâce à sa conception légère et stable, il permet de maintenir votre smartphone en position verticale ou inclinée selon vos besoins. Que ce soit pour regarder des vidéos, passer des appels en visioconférence, suivre une recette en cuisine ou consulter vos notifications sans avoir à tenir votre appareil en main, ce support vous assure un confort d’utilisation optimal. L’impression 3D de qualité garantit des finitions soignées et des lignes nettes, tandis que le PLA utilisé pour sa fabrication offre à la fois légèreté et solidité. Le coloris orange vif apporte une touche de couleur dynamique et contemporaine à votre espace de travail ou de détente. Compatible avec la majorité des modèles de téléphones, ce support est également facile à transporter et à ranger grâce à ses dimensions compactes. Fabriqué à partir de PLA, un matériau respectueux de l’environnement issu de ressources végétales renouvelables, il conjugue utilité quotidienne et engagement écologique. Idéal pour un usage personnel ou comme idée cadeau pratique et originale, ce support de téléphone imprimé en 3D séduit par sa simplicité, son efficacité et son design affirmé. La console sur l'image de présentation n'est pas incluse avec le support. Dimensions (en mm): L 100 l 90 h 90. Poids (en gr): 65.", 6.00, 2, "Aucun"),
(37, "Tirelire animal", "Apportez une touche de douceur et d’originalité à votre décoration intérieure avec ces adorables tirelires en forme d''ourson, entièrement imprimées en 3D. Conçues en PLA, un matériau écologique et résistant, ces tirelires séduisent par leur texture soignée qui imite l’aspect d’un tricot en laine, leur donnant un charme réconfortant et original. Ce duo se compose d’un petit chat bleu-violet aux traits minimalistes et attendrissants, et d’un charmant ourson crème aux oreilles rondes et à la truffe noire brillante. Chaque modèle présente des finitions impeccables et des détails soigneusement travaillés, comme les oreilles, les moustaches et les pattes, contribuant à leur aspect à la fois ludique et décoratif. La fente discrète située sur le dessus permet de glisser aisément pièces et billets, tandis qu’une ouverture astucieuse sous leur base permet de récupérer facilement le contenu sans abîmer l’objet. Ces tirelires sont idéales pour les chambres d’enfants, les bureaux, ou pour offrir un cadeau personnalisé et original à l’occasion d’un anniversaire ou d’une naissance. Fabriquées en impression 3D avec précision, elles sont légères, solides et respectueuses de l’environnement grâce à l’utilisation de PLA, un plastique biosourcé dérivé d’amidon de maïs. Un objet déco aussi pratique qu’attachant, à adopter sans hésiter !", 9.00, 2, "Aucun"),
(38, "Tirelire cochon", "Ajoutez une touche d’humour et de tendresse à votre décoration grâce à cette adorable tirelire cochon, imprimée en 3D avec soin à partir de PLA rose pâle. Son design minimaliste et épuré séduit par ses lignes douces et arrondies, qui rappellent les jouets vintage tout en conservant une esthétique résolument contemporaine. Le petit museau blanc, les oreilles pointues et la queue en spirale discrètement gravée à l’arrière apportent une note ludique et charmante à cet objet décoratif. La fente, située sur le dessus de la tirelire, permet de glisser facilement pièces et billets, et une ouverture sous sa base offre un accès rapide et pratique à son contenu. Parfaite pour décorer une chambre d’enfant, un bureau ou offrir en cadeau à l’occasion d’une naissance ou d’un anniversaire, cette tirelire allie fonctionnalité et originalité. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, elle est à la fois légère et résistante, avec un aspect légèrement satiné dû à l’impression 3D qui lui confère un charme artisanal. Un objet aussi décoratif que pratique, qui ravira petits et grands collectionneurs de tirelires ou d’objets imprimés en 3D ! Dimensions (en mm): L 140 l 120 h 110. Poids (en gr): 120.", 9.00, 2, "Aucun"),
(39, "Tirelire fusée", "Offrez une façon ludique et originale de mettre de l’argent de côté avec cette tirelire en forme de fusée, entièrement imprimée en 3D. Fabriquée en PLA de qualité, cette création se distingue par ses couleurs vives et sa finition soignée : une structure principale verte, des pieds et ailettes bleus, ainsi que des embouts de pieds jaunes, pour un ensemble joyeux et plein de caractère. Son design évoque une fusée rétro tout droit sortie d’un dessin animé ou d’un univers de science-fiction, avec ses formes arrondies, ses détails de rivets et ses pieds stabilisateurs. La fente située sur le haut permet d’insérer facilement pièces et billets. Idéale pour encourager petits et grands à économiser, cette tirelire décorative trouvera parfaitement sa place dans une chambre d’enfant, un bureau ou une étagère. L’impression 3D assure des finitions nettes et des détails précis. Fabriquée en PLA, un matériau biosourcé à base d’amidon de maïs, elle conjugue esthétique, robustesse et engagement écologique. Facile à ouvrir pour récupérer son contenu, elle combine aspect pratique et design original, et constitue une excellente idée cadeau pour les amateurs d’objets insolites, de décoration geek ou de pièces uniques imprimées en 3D.", 9.00, 2, "Aucun"),
(40, "Tortue", "Apportez une touche naturelle et élégante à votre décoration avec cette tortue décorative imprimée en 3D en PLA vert. Conçue avec soin, cette pièce met en valeur les formes douces et équilibrées de la carapace et des pattes, offrant un rendu à la fois sobre et raffiné. Sa couleur verte satinée évoque la nature et la sérénité, ce qui en fait un choix idéal pour agrémenter un bureau, une étagère ou un espace de vie. La qualité de son impression 3D et la finesse des détails soulignent la modernité de cet objet décoratif, qui saura également trouver sa place dans un cadre professionnel ou commercial. Fabriquée en PLA, un matériau biosourcé et respectueux de l’environnement, cette tortue est à la fois légère, solide et durable. Elle constitue ainsi un objet de décoration original et responsable, adapté à différents styles d’intérieurs et ambiances.", 4.00, 1, "Aucun"),
(41, "Toupie", "Découvrez cette toupie décorative imprimée en 3D en PLA bleu-violet, au design inspiré du volant d’un bateau. Sa forme élégante et symétrique évoque à la fois la précision mécanique et l’esthétique maritime, en faisant un objet original à exposer ou à utiliser en décoration. Conçue avec minutie, cette toupie offre un rendu soigné grâce à la qualité de son impression 3D et à la profondeur de sa teinte bleu-violet satinée. Son design circulaire et ajouré rappelle les gouvernails traditionnels des navires, apportant une note d’inspiration nautique à votre intérieur. Fabriquée en PLA, un matériau biosourcé à la fois solide et respectueux de l’environnement, cette pièce décorative s’intègre aussi bien dans un bureau, un salon ou un espace de travail. Elle peut également être proposée comme objet de collection ou élément de vitrine dans un cadre commercial ou événementiel.", 3.50, 3, "Aucun"),
(42, "Vide poche", "Apportez une touche d’organisation élégante à votre intérieur avec ce vide-poche imprimé en 3D en PLA. Parfait pour accueillir clés, pièces, bijoux ou petits objets du quotidien, il allie praticité et design soigné pour garder vos espaces ordonnés avec style. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce vide-poche allie légèreté, robustesse et finition satinée, mettant en valeur ses formes harmonieuses et sa surface lisse. Compact et polyvalent, il trouve facilement sa place sur une console, une table basse, une commode ou un bureau. Disponible en plusieurs coloris, il s’intègre aisément à des ambiances modernes, minimalistes ou naturelles. Ce vide-poche est un accessoire fonctionnel et esthétique, idéal pour organiser votre quotidien tout en apportant une touche déco discrète et raffinée. Dimensions (en mm): L 140 l 140 h 70. Poids (en gr): 100.", 6.00, 2, "Aucun"),
(43, "Support de manette jeux", "Mettez en valeur votre configuration de jeu avec ce support de manette unique, spécialement conçu pour allier fonctionnalité et esthétique. Imprimé en 3D avec soin à partir de PLA de qualité, ce support arbore une teinte rouge-orange saisissante qui attire instantanément le regard et apporte une touche dynamique à votre espace gaming. Son design original et travaillé présente une base aux lignes géométriques inspirées des structures cristallines, offrant à la fois stabilité et élégance. Sur cette base repose une manette stylisée, décorée de symboles de boutons et d’une illustration cartoon d’un primate malicieux, clin d’œil assumé aux univers vidéoludiques et à l’imaginaire rétro-gaming. Ce support est parfaitement adapté pour accueillir et exposer vos manettes lorsque vous ne les utilisez pas, évitant ainsi qu’elles traînent sur le bureau ou les étagères. Idéal pour maintenir l’ordre dans votre espace tout en valorisant vos accessoires de jeu, il s’intègre facilement dans une chambre, un salon ou un bureau grâce à son esthétique soignée et son rendu moderne. Fabriqué en PLA, un matériau léger, solide et respectueux de l’environnement issu de ressources renouvelables, ce support associe utilité et démarche responsable. Il constitue également un excellent cadeau pour les amateurs de jeux vidéo et les collectionneurs d’accessoires gaming originaux. Que ce soit pour sublimer votre installation ou offrir un présent original et pratique, ce support de manette imprimé en 3D répondra à toutes les attentes. La manette sur l'image de présentation n'est pas incluse avec le support. Dimensions (en mm): L 75 l 75 h 165. Poids (en gr): 105.", 7.00, 3, "Aucun"),
(44, "Présentoir boucles d'oreilles hexagonal", "Mettez en avant vos boucles d’oreilles avec ce présentoir hexagonal au design moderne, imprimé en 3D avec précision à partir de PLA respectueux de l’environnement. Sa forme géométrique unique offre une présentation originale et élégante, permettant de disposer vos bijoux de manière ordonnée et esthétique. L’impression 3D garantit des finitions soignées et un rendu homogène, valorisant chaque détail du présentoir. Fabriqué en PLA biodégradable, ce support allie durabilité et engagement écologique. Adapté à un usage personnel, en boutique ou lors d’expositions, il s’intègre parfaitement dans tout type de décor et constitue une idée de cadeau distinguée pour les amateurs de bijoux et de créations artisanales. Les bijoux sur l'image de présentation ne sont pas inclus avec le support. Dimensions (en mm): L 140 l 120 h 135. Poids (en gr): 32.", 4.00, 2, "Aucun"),
(45, "Présentoir boucles d'oreilles rond", "Exposez vos boucles d’oreilles avec élégance grâce à ce présentoir de forme ronde, imprimé en 3D avec précision à partir de PLA respectueux de l’environnement. Son design circulaire et épuré permet de présenter divers styles de boucles d’oreilles de façon ordonnée et esthétique. L’impression 3D garantit des finitions nettes et un rendu homogène, mettant en valeur chaque détail du présentoir. Fabriqué en PLA biodégradable, ce support allie durabilité et engagement écologique. Parfait pour un usage personnel, une boutique ou une exposition, il s’intègre harmonieusement dans tout type de décor et constitue une idée de cadeau raffinée pour les amateurs de bijoux ou d’objets imprimés en 3D. Les bijoux sur l'image de présentation ne sont pas inclus avec le support. Dimensions (en mm): L 150 l 10 h 140. Poids (en gr): 28.", 4.00, 2, "Aucun"),
(46, "Présentoir colliers", "Mettez en valeur vos bijoux avec ce présentoir à colliers au design élégant, imprimé en 3D avec précision à partir de PLA écologique. Sa forme étudiée permet de disposer colliers, chaînes ou pendentifs de manière ordonnée, tout en les exposant avec raffinement. Grâce à l’impression 3D, les lignes sont nettes et les finitions soignées, offrant un rendu visuel harmonieux et professionnel. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce présentoir combine esthétique et démarche durable. Idéal pour une utilisation personnelle, en boutique ou lors d’expositions, il s’intègre facilement dans tout type de décoration et constitue également une idée de cadeau originale pour les amateurs de bijoux ou de créations artisanales. Les bijoux sur l'image de présentation ne sont pas inclus avec le support.", 4.00, 2, "Aucun"),
(47, "Support boule de noël", "Apportez une touche raffinée et festive à votre décoration de fin d’année avec ce support de boule de Noël imprimé en 3D en PLA. Conçu pour mettre en valeur vos boules de Noël préférées, il allie élégance et stabilité pour sublimer vos décorations avec délicatesse. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce support allie légèreté, robustesse et finition satinée, mettant en valeur ses lignes épurées et son design soigné. Compact et stable, il s’adapte à différents formats de boules de Noël, offrant une présentation harmonieuse sur une table, une étagère ou un manteau de cheminée. Disponible en plusieurs coloris, il s’intègre facilement à des ambiances festives, modernes ou classiques. Ce support de boule de Noël est un accessoire décoratif pratique et élégant, idéal pour magnifier votre sapin ou vos mises en scène de saison. La boule de noël sur l'image de présentation n'est pas incluse avec le support.", 4.00, 4, "Aucun"),
(48, "Support bouteille", "Ajoutez une touche contemporaine et élégante à votre espace avec ce porte-bouteille flottant moderne imprimé en 3D en PLA. Son design minimaliste et suspendu crée l’illusion d’une bouteille en lévitation, apportant un effet visuel unique et raffiné à votre décoration intérieure. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce porte-bouteille allie légèreté, robustesse et finition satinée, mettant en valeur ses lignes épurées et son esthétique moderne. Personnalisable, il s’adapte parfaitement à vos goûts et à votre style, devenant un véritable objet décoratif autant qu’un support fonctionnel. Facile à installer, il s’intègre harmonieusement dans une cuisine, une salle à manger ou un bar, valorisant votre collection de vins ou spiritueux tout en optimisant l’espace. Disponible en plusieurs coloris, ce porte-bouteille flottant est un choix design et pratique, idéal pour offrir un cadeau original et personnalisé aux amateurs de vin. La bouteille sur l'image de présentation n'est pas incluse avec le support. Dimensions (en mm): L 280 l 60 h 60. Poids (en gr): 60.", 6.00, 2, "Aucun"),
(49, "Support verres sur bouteille", "Apportez une touche d’élégance et de convivialité à vos moments de dégustation avec ce porte-verres sur bouteille imprimé en 3D en PLA. Conçu pour se fixer facilement autour du goulot, il permet de suspendre élégamment deux verres, alliant praticité et design raffiné pour sublimer votre service. Fabriqué en PLA, un matériau biosourcé et respectueux de l’environnement, ce support allie légèreté, robustesse et finition satinée, mettant en valeur ses lignes épurées et sa conception soignée. Son format compact et stable assure une fixation sécurisée tout en facilitant le transport et la présentation de vos verres. Disponible en plusieurs coloris modernes, il s’intègre harmonieusement dans des ambiances contemporaines, chaleureuses ou festives. Ce porte-verres sur bouteille est un accessoire aussi esthétique que fonctionnel, idéal pour offrir un cadeau élégant ou embellir vos apéritifs et repas entre amis. La bouteille et les verres sur l'image de présentation ne sont pas inclus avec le support. Dimensions (en mm): L 210 l 100 h 8. Poids (en gr): 50.", 5.00, 2, "Aucun"),
(50, "Support de Switch", "Optimisez votre espace de jeu avec ce support pour console Nintendo Switch, imprimé en 3D avec précision à partir de PLA de qualité. Conçu pour maintenir la console de manière stable et sécurisée, son design fonctionnel et soigné allie ergonomie et modernité. Grâce à l’impression 3D, chaque courbe et angle est travaillé avec minutie pour garantir un rendu homogène, durable et esthétique. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce support s’inscrit dans une démarche responsable tout en répondant aux exigences des joueurs. Parfait pour une installation propre et organisée, il convient aussi bien à un bureau, une étagère ou un meuble TV, et peut faire office de cadeau pratique pour les passionnés de jeux vidéo ou les amateurs d’accessoires imprimés en 3D. La console sur l'image de présentation n'est pas incluse avec le support.", 6.00, 2, "Aucun"),
(51, "Pot à crayons oval", "Ajoutez une touche moderne et fonctionnelle à votre espace de travail avec ce pot à crayons ovale, imprimé en 3D avec précision à partir de PLA écologique. Son design épuré et ses lignes douces apportent une esthétique sobre et contemporaine, idéale pour organiser stylos, pinceaux ou accessoires de bureau. Grâce à l’impression 3D, chaque courbe est soigneusement définie pour un rendu homogène et de qualité. Fabriqué en PLA, un matériau biodégradable et respectueux de l’environnement, ce pot combine utilité et engagement durable. Il trouvera naturellement sa place sur un bureau, dans un atelier ou une chambre d’enfant, et constitue également une idée de cadeau utile et originale pour les amateurs d’objets design et responsables. Dimensions (en mm): L 110 l 115 h 91.", 5.00, 2, "Aucun"),
(154, "Petit dinosaure", "Plongez dans l’univers fascinant de la préhistoire avec cette figurine de dinosaure, une pièce décorative imprimée en 3D avec précision à partir de PLA de qualité. Son design réaliste et ses lignes détaillées en font un objet aussi captivant qu’esthétique, parfait pour agrémenter une chambre, un bureau ou une bibliothèque. Grâce à la technologie d’impression 3D, chaque relief est fidèlement reproduit pour offrir un rendu homogène et soigneux. Conçue en PLA, un matériau biodégradable et respectueux de l’environnement, cette figurine allie durabilité et conscience écologique. Elle s’intégrera harmonieusement dans un intérieur contemporain, éducatif ou thématique, et constitue également une excellente idée de cadeau pour les passionnés de dinosaures, les enfants, les amateurs de modélisme ou de créations artisanales en impression 3D.", 3.00, 1, "Aucun");

INSERT INTO image (id, path, product_id)
VALUES 
(1, "bloque_page_1.jpg", 1),
(2, "pot_fleur_rond_1.jpg", 2),
(3, "chat_allonge_1.jpg", 3),
(4, "chiot_1.jpg", 4),
(5, "ecureuil_1.jpg", 5),
(6, "lapin_1.jpg", 6),
(7, "lion_1.jpg", 7),
(8, "panda_1.jpg", 8),
(9, "pokeball_arcanin_1.jpg", 9),
(10, "pokeball_ronflex_1.jpg", 10),
(11, "pot_fleur_chien_1.jpg", 11),
(12, "sifflet_1.jpg", 12),
(13, "boite_brosse_a_dents_1.jpg", 13),
(14, "chat_1.jpg", 14),
(15, "chien_flex_1.jpg", 15),
(16, "coquetier_1.jpg", 16),
(17, "cube_infini_1.jpg", 17),
(18, "dinosaure_1.jpg", 18),
(19, "lapin_yeux_fermes_1.jpg", 19),
(20, "lapin_yeux_ouverts_1.jpg", 20),
(21, "licorne_flex_1.jpg", 21),
(22, "morpion_1.jpg", 22),
(23, "oeuf_deco_1.jpg", 23),
(24, "ouvre_bouteille_1.jpg", 24),
(25, "pancarte_semis_1.jpg", 25),
(26, "pion_echec_1.jpg", 26),
(27, "porte_cartes_1.jpg", 27),
(28, "porte_cartes_visite_1.jpg", 28),
(29, "porte_crayons_rond_1.jpg", 29),
(30, "pot_fleur_pentagone_1.jpg", 30),
(31, "pot_fleur_petit_1.jpg", 31),
(32, "poule_flex_1.jpg", 32),
(33, "sapin_1.jpg", 33),
(34, "support_brosse_a_dents_1.jpg", 34),
(35, "support_cassette_switch_1.jpg", 35),
(36, "support_ecran_1.jpg", 36),
(37, "tirelire_animal_1.jpg", 37),
(38, "tirelire_cochon_1.jpg", 38),
(39, "tirelire_fusee_1.jpg", 39),
(40, "tortue_1.jpg", 40),
(41, "toupie_1.jpg", 41),
(42, "vide_poche_1.jpg", 42),
(43, "support_manette_1.jpg", 43),
(44, "presentoir_boucles_oreilles_hexagonal_1.jpg", 44),
(45, "presentoir_boucles_oreilles_rond_1.jpg", 45),
(46, "presentoir_colliers_1.jpg", 46),
(47, "support_boule_noel_1.jpg", 47),
(48, "support_bouteille_1.jpg", 48),
(49, "support_bouteille_verres_1.jpg", 49),
(50, "support_switch_1.jpg", 50),
(51, "pot_crayons_oval_1.jpg", 51),
(52, "bloque_page_2.jpg", 1),
(53, "bloque_page_3.jpg", 1),
(54, "pot_fleur_rond_2.jpg", 2),
(55, "pot_fleur_rond_3.jpg", 2),
(56, "chat_allonge_2.jpg", 3),
(57, "chat_allonge_3.jpg", 3),
(58, "chiot_2.jpg", 4),
(59, "chiot_3.jpg", 4),
(60, "ecureuil_2.jpg", 5),
(61, "ecureuil_3.jpg", 5),
(62, "lapin_2.jpg", 6),
(63, "lapin_3.jpg", 6),
(64, "lion_2.jpg", 7),
(65, "lion_3.jpg", 7),
(66, "panda_2.jpg", 8),
(67, "panda_3.jpg", 8),
(68, "pokeball_arcanin_2.jpg", 9),
(69, "pokeball_arcanin_3.jpg", 9),
(70, "pokeball_ronflex_2.jpg", 10),
(71, "pokeball_ronflex_3.jpg", 10),
(72, "pot_fleur_chien_2.jpg", 11),
(73, "pot_fleur_chien_3.jpg", 11),
(74, "sifflet_2.jpg", 12),
(75, "sifflet_3.jpg", 12),
(76, "boite_brosse_a_dents_2.jpg", 13),
(77, "boite_brosse_a_dents_3.jpg", 13),
(78, "chat_2.jpg", 14),
(79, "chat_3.jpg", 14),
(80, "chien_flex_2.jpg", 15),
(81, "chien_flex_3.jpg", 15),
(82, "coquetier_2.jpg", 16),
(83, "coquetier_3.jpg", 16),
(84, "cube_infini_2.jpg", 17),
(85, "cube_infini_3.jpg", 17),
(86, "dinosaure_2.jpg", 18),
(87, "dinosaure_3.jpg", 18),
(88, "lapin_yeux_fermes_2.jpg", 19),
(89, "lapin_yeux_fermes_3.jpg", 19),
(90, "lapin_yeux_ouverts_2.jpg", 20),
(91, "lapin_yeux_ouverts_3.jpg", 20),
(92, "licorne_flex_2.jpg", 21),
(93, "licorne_flex_3.jpg", 21),
(94, "morpion_2.jpg", 22),
(95, "morpion_3.jpg", 22),
(96, "oeuf_deco_2.jpg", 23),
(97, "oeuf_deco_3.jpg", 23),
(98, "ouvre_bouteille_2.jpg", 24),
(99, "ouvre_bouteille_3.jpg", 24),
(100, "pancarte_semis_2.jpg", 25),
(101, "pancarte_semis_3.jpg", 25),
(102, "pion_echec_2.jpg", 26),
(103, "pion_echec_3.jpg", 26),
(104, "porte_cartes_2.jpg", 27),
(105, "porte_cartes_3.jpg", 27),
(106, "porte_cartes_visite_2.jpg", 28),
(107, "porte_cartes_visite_3.jpg", 28),
(108, "porte_crayons_rond_2.jpg", 29),
(109, "porte_crayons_rond_3.jpg", 29),
(110, "pot_fleur_pentagone_2.jpg", 30),
(111, "pot_fleur_pentagone_3.jpg", 30),
(112, "pot_fleur_petit_2.jpg", 31),
(113, "pot_fleur_petit_3.jpg", 31),
(114, "poule_flex_2.jpg", 32),
(115, "poule_flex_3.jpg", 32),
(116, "sapin_2.jpg", 33),
(117, "sapin_3.jpg", 33),
(118, "support_brosse_a_dents_2.jpg", 34),
(119, "support_brosse_a_dents_3.jpg", 34),
(120, "support_cassette_switch_2.jpg", 35),
(121, "support_cassette_switch_3.jpg", 35),
(122, "support_ecran_2.jpg", 36),
(123, "support_ecran_3.jpg", 36),
(124, "tirelire_animal_2.jpg", 37),
(125, "tirelire_animal_3.jpg", 37),
(126, "tirelire_cochon_2.jpg", 38),
(127, "tirelire_cochon_3.jpg", 38),
(128, "tirelire_fusee_2.jpg", 39),
(129, "tirelire_fusee_3.jpg", 39),
(130, "tortue_2.jpg", 40),
(131, "tortue_3.jpg", 40),
(132, "toupie_2.jpg", 41),
(133, "toupie_3.jpg", 41),
(134, "vide_poche_2.jpg", 42),
(135, "vide_poche_3.jpg", 42),
(136, "support_manette_2.jpg", 43),
(137, "support_manette_3.jpg", 43),
(138, "presentoir_boucles_oreilles_hexagonal_2.jpg", 44),
(139, "presentoir_boucles_oreilles_hexagonal_3.jpg", 44),
(140, "presentoir_boucles_oreilles_rond_2.jpg", 45),
(141, "presentoir_boucles_oreilles_rond_3.jpg", 45),
(142, "presentoir_colliers_2.jpg", 46),
(143, "presentoir_colliers_3.jpg", 46),
(144, "support_boule_noel_2.jpg", 47),
(145, "support_boule_noel_3.jpg", 47),
(146, "support_bouteille_2.jpg", 48),
(147, "support_bouteille_3.jpg", 48),
(148, "support_bouteille_verres_2.jpg", 49),
(149, "support_bouteille_verres_3.jpg", 49),
(150, "support_switch_2.jpg", 50),
(151, "support_switch_3.jpg", 50),
(152, "pot_crayons_oval_2.jpg", 51),
(153, "pot_crayons_oval_3.jpg", 51),
(154, "dinosaure_flex_1.jpg", 154),
(155, "dinosaure_flex_2.jpg", 154),
(156, "dinosaure_flex_3.jpg", 154);





